### obtener todos los characters
GET http://localhost:3000/api/medicalHistory

### obtener un character

GET http://localhost:3000/api/medicalHistory/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/medicalHistory
Content-Type: application/json

{
    "petId": 3,
    "observations": ["17/6: Se aplicó vacuna numero 1"],
    "vaccines": [1]
}
###modificar un  character  (PUT)
PUT http://localhost:3000/api/medicalHistory/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "petId": 18,
    "observations": ["17/6: Se aplicó vacuna numero 1 y 2"],
    "vaccines": [1,2],
    "id": "a02b91bc-3769-4221-beb1-d7a3aeba7dad"
}

###modificar un  character parcialmente (PATCH)
PATCH http://localhost:3000/api/medicalHistory/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "observations": ["17/6: Se aplicó vacuna numero 1 y 2", "18/6 vacuna 4"],
    "vaccines": [1,2,3,4]
}

###borrar un character

DELETE http://localhost:3000/api/medicalHistory/a02b91bc-3769-4221-beb1-d7a3aeba7dad